{% set name = "terraform" %}
{% set version = "1.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hashicorp/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 817a70beb9f01b356618512b24eca6b3c0b311acb2fdf2e875bedb9c8d5b496d

build:
  number: 0
  script:
    - go build -v -ldflags "-w -s -X 'github.com/hashicorp/terraform/version.dev=no'" -o $PREFIX/bin/terraform  # [not win]
    - go install -v -ldflags "-w -s -X 'github.com/hashicorp/terraform/version.dev=no'" .                       # [win]

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('go') }}

test:
  commands:
    - terraform -v

about:
  home: https://www.terraform.io
  license: BUSL-1.1
  license_file: LICENSE
  summary: Terraform is a tool for building, changing, and combining infrastructure safely and efficiently.
  description: |
    Terraform is a tool for building, changing, and versioning infrastructure safely and 
    efficiently. Terraform can manage existing and popular service providers as well as custom in-house 
    solutions.
  doc_url: https://www.terraform.io/docs/index.html
  dev_url: https://github.com/hashicorp/terraform.git

extra:
  recipe-maintainers:
    - sodre
    - mariusvniekerk
    - dhirschfeld
    - oblute
    - rluria14
    - ndmaxar
