{% set name = "terraform" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hashicorp/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 4124593de269bfcfdeb0481a471a842a5dbfc34ac1796252c8c54a44d5da8c33

build:
  number: 0
  script:
    - go install -v .

requirements:
  build:
    - {{ compiler('go') }} 1.13

test:
  commands:
    - terraform -v

about:
  home: https://www.terraform.io
  license: MPL-2.0
  summary: Terraform is a tool for building, changing, and combining infrastructure safely and efficiently.
  description: |
    Terraform is a tool for building, changing, and versioning infrastructure safely and 
    efficiently. Terraform can manage existing and popular service providers as well as custom in-house 
    solutions.
  doc_url: https://www.terraform.io/docs/index.html
  dev_url: https://github.com/hashicorp/terraform.git

extra:
  recipe-maintainers:
    - sodre
    - mariusvniekerk
    - dhirschfeld
    - oblute
    - rluria14
    - ndmaxar
