# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "f4W+xLJ/WjpZv/baS/B2NkGhNKe79iGSGehamAYCtM9Nh0Nf/ZILbCa/LbcqxT6irPcBzbCng1KmbCr72Cwoi3LfcMzJ8Jgdxm+KeodbvhNHis5IbQ7233sDQbCL9oqSAryojXbiouPlXOYjJ6QX1i0NKbF7DsUz6iqNXdz89qnTM+fqHwPFhtV3TADfxr2Kiwc02L2bdLaFlnJGQPhqOb/QePd+rW18Jvy3lhybS6GPuIij0S/rk0ThmBOXzcrm5PzBmQx19VLs1AIsj0gpRvcG0mzC4EwD+rpqMwBBC6MdC6h3Q1NvqSKDs+213F7k+/QBWLrI9XtRRaJx2KQ4G/ty13PAF/RX6yaMCLhirlaQidhGMhbYLeFWZjvi4BS7iyZXI6A+zTl5s8q4qnX0hesJBluxgD9jkD3oSPybPTyYyhvGsYX9Uz19W0Z40+kUjHbmah663KkgZd5xVile+PtUrie4HiXVgjyzkq3Gr0FLbk4BvM71ntj/hCGwbIGnF/sTcfzWDa91Cxjk6K3ZRp8wn1ymQvfutu1arnDnZdmR6Mtm43KfyXA3E0MnnckHBTgiKslFQnyFufKzXYfjSZjdYTtLwNKFHVPMwosnobUfhVRhWf70MTG+QFjyTYPtGNPHmk+E9pVafxIwbrB/oNTFHBvGIY7BpKEIJq3TAGY="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
