appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: f4W+xLJ/WjpZv/baS/B2NkGhNKe79iGSGehamAYCtM9Nh0Nf/ZILbCa/LbcqxT6irPcBzbCng1KmbCr72Cwoi3LfcMzJ8Jgdxm+KeodbvhNHis5IbQ7233sDQbCL9oqSAryojXbiouPlXOYjJ6QX1i0NKbF7DsUz6iqNXdz89qnTM+fqHwPFhtV3TADfxr2Kiwc02L2bdLaFlnJGQPhqOb/QePd+rW18Jvy3lhybS6GPuIij0S/rk0ThmBOXzcrm5PzBmQx19VLs1AIsj0gpRvcG0mzC4EwD+rpqMwBBC6MdC6h3Q1NvqSKDs+213F7k+/QBWLrI9XtRRaJx2KQ4G/ty13PAF/RX6yaMCLhirlaQidhGMhbYLeFWZjvi4BS7iyZXI6A+zTl5s8q4qnX0hesJBluxgD9jkD3oSPybPTyYyhvGsYX9Uz19W0Z40+kUjHbmah663KkgZd5xVile+PtUrie4HiXVgjyzkq3Gr0FLbk4BvM71ntj/hCGwbIGnF/sTcfzWDa91Cxjk6K3ZRp8wn1ymQvfutu1arnDnZdmR6Mtm43KfyXA3E0MnnckHBTgiKslFQnyFufKzXYfjSZjdYTtLwNKFHVPMwosnobUfhVRhWf70MTG+QFjyTYPtGNPHmk+E9pVafxIwbrB/oNTFHBvGIY7BpKEIJq3TAGY=}
provider:
  win: azure
bot:
  automerge: true
